// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEbrNgFr4onH9aacgNU5CWenquQrdzUBk',
    appId: '1:181318808210:web:c6c81b0f3d1a4b06cfac4b',
    messagingSenderId: '181318808210',
    projectId: 'matjar-7419d',
    authDomain: 'matjar-7419d.firebaseapp.com',
    storageBucket: 'matjar-7419d.firebasestorage.app',
    measurementId: 'G-1DKQLFM7JZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvXFTACE5exJm0NqeJpONRp8mliWsJVHY',
    appId: '1:181318808210:android:56ad7bfe4a636b17cfac4b',
    messagingSenderId: '181318808210',
    projectId: 'matjar-7419d',
    storageBucket: 'matjar-7419d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpvb5HoOrxzVkMzO5UbemeaEyTwLYDwJ0',
    appId: '1:181318808210:ios:707317e22a448974cfac4b',
    messagingSenderId: '181318808210',
    projectId: 'matjar-7419d',
    storageBucket: 'matjar-7419d.firebasestorage.app',
    iosBundleId: 'com.example.shopMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpvb5HoOrxzVkMzO5UbemeaEyTwLYDwJ0',
    appId: '1:181318808210:ios:707317e22a448974cfac4b',
    messagingSenderId: '181318808210',
    projectId: 'matjar-7419d',
    storageBucket: 'matjar-7419d.firebasestorage.app',
    iosBundleId: 'com.example.shopMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEbrNgFr4onH9aacgNU5CWenquQrdzUBk',
    appId: '1:181318808210:web:452b588fb15805a8cfac4b',
    messagingSenderId: '181318808210',
    projectId: 'matjar-7419d',
    authDomain: 'matjar-7419d.firebaseapp.com',
    storageBucket: 'matjar-7419d.firebasestorage.app',
    measurementId: 'G-VLX98Y5V19',
  );

}